version: '3.8'

services:
  auth_service:
    build: .
    container_name: auth_service
    ports:
      - "9001:9001"
    environment:
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
